POKEMONS_DB = [
    # --- PRIMERA GENERACION (KANTO) ---
    {"id": 1, "name": "Bulbasaur", "type": "Planta/Veneno", "level": 5, "hp": 45},
    {"id": 2, "name": "Ivysaur", "type": "Planta/Veneno", "level": 16, "hp": 60},
    {"id": 3, "name": "Venusaur", "type": "Planta/Veneno", "level": 32, "hp": 80},
    {"id": 4, "name": "Charmander", "type": "Fuego", "level": 5, "hp": 39},
    {"id": 5, "name": "Charmeleon", "type": "Fuego", "level": 16, "hp": 58},
    {"id": 6, "name": "Charizard", "type": "Fuego/Volador", "level": 36, "hp": 78},
    {"id": 7, "name": "Squirtle", "type": "Agua", "level": 5, "hp": 44},
    {"id": 8, "name": "Wartortle", "type": "Agua", "level": 16, "hp": 59},
    {"id": 9, "name": "Blastoise", "type": "Agua", "level": 36, "hp": 79},
    {"id": 10, "name": "Caterpie", "type": "Bicho", "level": 3, "hp": 45},
    {"id": 25, "name": "Pikachu", "type": "Electrico", "level": 12, "hp": 35},
    {"id": 26, "name": "Raichu", "type": "Electrico", "level": 30, "hp": 60},
    {"id": 133, "name": "Eevee", "type": "Normal", "level": 15, "hp": 55},
    {"id": 143, "name": "Snorlax", "type": "Normal", "level": 30, "hp": 160},
    {"id": 150, "name": "Mewtwo", "type": "Psiquico", "level": 70, "hp": 106},
    {"id": 151, "name": "Mew", "type": "Psiquico", "level": 50, "hp": 100},

    # --- SEGUNDA GENERACION (JOHTO) ---
    {"id": 152, "name": "Chikorita", "type": "Planta", "level": 5, "hp": 45},
    {"id": 155, "name": "Cyndaquil", "type": "Fuego", "level": 5, "hp": 39},
    {"id": 158, "name": "Totodile", "type": "Agua", "level": 5, "hp": 50},
    {"id": 161, "name": "Sentret", "type": "Normal", "level": 4, "hp": 35},
    {"id": 179, "name": "Mareep", "type": "Electrico", "level": 6, "hp": 55},
    {"id": 196, "name": "Espeon", "type": "Psiquico", "level": 25, "hp": 65},
    {"id": 197, "name": "Umbreon", "type": "Siniestro", "level": 25, "hp": 95},
    {"id": 212, "name": "Scizor", "type": "Bicho/Acero", "level": 30, "hp": 70},
    {"id": 248, "name": "Tyranitar", "type": "Roca/Siniestro", "level": 55, "hp": 100},
    {"id": 249, "name": "Lugia", "type": "Psiquico/Volador", "level": 70, "hp": 106},
    {"id": 250, "name": "Ho-Oh", "type": "Fuego/Volador", "level": 70, "hp": 106},

    # --- TERCERA GENERACION (HOENN) ---
    {"id": 252, "name": "Treecko", "type": "Planta", "level": 5, "hp": 40},
    {"id": 255, "name": "Torchic", "type": "Fuego", "level": 5, "hp": 45},
    {"id": 258, "name": "Mudkip", "type": "Agua", "level": 5, "hp": 50},
    {"id": 263, "name": "Zigzagoon", "type": "Normal", "level": 3, "hp": 38},
    {"id": 280, "name": "Ralts", "type": "Psiquico/Hada", "level": 4, "hp": 28},
    {"id": 287, "name": "Slakoth", "type": "Normal", "level": 5, "hp": 60},
    {"id": 330, "name": "Flygon", "type": "Tierra/Dragon", "level": 45, "hp": 80},
    {"id": 373, "name": "Salamence", "type": "Dragon/Volador", "level": 50, "hp": 95},
    {"id": 376, "name": "Metagross", "type": "Acero/Psiquico", "level": 50, "hp": 80},
    {"id": 382, "name": "Kyogre", "type": "Agua", "level": 70, "hp": 100},
    {"id": 383, "name": "Groudon", "type": "Tierra", "level": 70, "hp": 100},
    {"id": 384, "name": "Rayquaza", "type": "Dragon/Volador", "level": 70, "hp": 105},

    # --- CUARTA GENERACION (SINNOH) ---
    {"id": 387, "name": "Turtwig", "type": "Planta", "level": 5, "hp": 55},
    {"id": 390, "name": "Chimchar", "type": "Fuego", "level": 5, "hp": 44},
    {"id": 393, "name": "Piplup", "type": "Agua", "level": 5, "hp": 53},
    {"id": 396, "name": "Starly", "type": "Normal/Volador", "level": 3, "hp": 40},
    {"id": 399, "name": "Bidoof", "type": "Normal", "level": 4, "hp": 59},
    {"id": 403, "name": "Shinx", "type": "Electrico", "level": 5, "hp": 45},
    {"id": 425, "name": "Drifloon", "type": "Fantasma/Volador", "level": 15, "hp": 90},
    {"id": 442, "name": "Spiritomb", "type": "Fantasma/Siniestro", "level": 25, "hp": 50},
    {"id": 445, "name": "Garchomp", "type": "Dragon/Tierra", "level": 48, "hp": 108},
    {"id": 448, "name": "Lucario", "type": "Lucha/Acero", "level": 35, "hp": 70},
    {"id": 461, "name": "Weavile", "type": "Siniestro/Hielo", "level": 38, "hp": 70},
    {"id": 479, "name": "Rotom", "type": "Electrico/Fantasma", "level": 20, "hp": 50},
]
